[package]
name = "tcp_ledger_service"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
byteorder = { version = "*", default-features = false }
micro_rpc = { workspace = true }
prost = { version = "0.11", default-features = false, features = ["prost-derive"] }
prost-types = { version = "*", default-features = false }

[build-dependencies]
micro_rpc_build = { workspace = true }