[workspace]
resolver = "2"
members = [
    "apps/atomic_counter/*",
    "apps/ledger/*",
    "apps/tablet_store/*",
    "apps/tablet_cache/*",
    "integration",
    "runtime",
    "proto"
]

[workspace.dependencies]
micro_rpc = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
micro_rpc_build = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
oak_attestation = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
oak_attestation_verification = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
oak_crypto = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
oak_enclave_runtime_support = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
oak_proto_rust = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
oak_restricted_kernel_sdk = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
oak_restricted_kernel_interface = { git = "https://github.com/project-oak/oak", rev = "319f9f97249c142abd7ad5038bdca24f90aeb515" }
# Temporarily point to the personal github repo, plan to migrate most of the trusted code to the Git on Borg.
raft = { git = "https://github.com/google/raft-rs", rev = "93c40a24182cd595a3f50103a83aee0bacd9881b", package = "raft", default-features = false, features = ["prost-codec"] }
raft-proto = { git = "https://github.com/google/raft-rs", rev = "93c40a24182cd595a3f50103a83aee0bacd9881b", package = "raft-proto", default-features = false, features = ["prost-codec"] }