[target.x86_64-unknown-none]
rustflags = "-C relocation-model=static -C code-model=small -C target-feature=+sse,+sse2,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+rdrand,-soft-float"

# A cargo environment variable holding the root directory of our repo.
# We can use WORKSPACE_ROOT instead of `std::env::current_dir()` to navigate in the repo.
[env]
WORKSPACE_ROOT = { value = "", relative = true }
