[package]
name = "cfc_crypto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
aes-gcm-siv = "*"
anyhow = { version = "*", default-features = false }
coset = { version = "*", default-features = false }
hpke = { version = "*" }

[dev-dependencies]
googletest = "*"
